name: Using a supersecret GHCR image

on:
  [workflow_dispatch]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Why hello there...
        uses: brianmmdev-that-actions/gcr-base-action@main
        with:
          name: Brian