name: Bash the user

on:
  [workflow_dispatch]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Why hello there...
        uses: brianmmdev-that-actions/docker-sh-action@main
        with:
          name: Brian