name: Using a dependent GHCR image

on:
  [workflow_dispatch]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/brianmmdev-that-actions/ghcr-base-image-with-dep:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Bash it!
        run: action-bin Brian