name: Using a supersecret GHCR image

on:
  [workflow_dispatch]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/brianmmdev-that-actions/ghcr-base-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Run it
        run: |
          action-bin Brian